# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2644ac528449b6ff6048a19a29b603bfe69a213325e2c6d02abc4bf4bc0b3e02c31cf7fa7cdf72a410e1befee39671310725f7f4815f46e9dde88bdbd78ce7c5

test:
  secret_key_base: d97d62168a83330ab248833e29de0e823894583d01bec528725d47f893f48cd53d5625c36fc4c786785984b5a6988c49467bf0ed09e0a5601da7e0e4fb2656ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
